def questions(question_num):

    """
    These questions are result generated by ChatGPT 3.5.
    Adjectives in comments are extracted and loaded to ChatGPT 3.5
    Command: "Based on the adjectives below, design 4 questions to ask the preference on Imperial IPA of a beer lover, in order to recommend a imperial IPA to him"
    """
    
    li_questions = [
        "Fruit Presence: Are you inclined towards Imperial IPAs that feature fruity notes like mango, peach, or citrus, or do you prefer a more neutral fruit profile?",
        "Mouthfeel: Do you enjoy Imperial IPAs with a thick, syrupy mouthfeel, or do you lean towards a lighter and more refreshing texture?",
        "Bitterness Level: Are you looking for a beer with intense bitterness, or do you prefer a smoother and less bitter experience in your Imperial IPAs?",
        "Alcohol Strength: Do you prefer Imperial IPAs with a higher alcohol content that adds warmth, or do you lean towards those with a more moderate ABV for a sessionable experience?"
    ]
    
    return li_questions[question_num]
